### ISSUE TITLE
Shared framework

### ISSUE THREAD

**Issue by AlexanderBaranowski** [jkolb/FieryCrucible#14]
latest release 2.0.3:
[21:57:29]: ▸ **\* Skipped building FieryCrucible due to the error:
[21:57:29]: ▸ Dependency "FieryCrucible" has no shared framework schemes for any of the platforms: iOS
2.0.2 works

**Comment by jkolb** [comment]
OK should have a fix up later tonight. Thanks for lettimg me know.

**Comment by jkolb** [comment]
Alright 2.0.4 seems to fix this, saw the shared scheme in Xcode so assumed it would work not realizing that the .gitignore was modified by SwiftPM to ignore xcodeproj changes which is where SwiftPM is storing Info.plist and the schemes.
