### ISSUE TITLE
Coca Pod support?

### ISSUE THREAD

**Issue by omerlh** [jkolb/FieryCrucible#15]
Hey
Are you planning to support cocoa pod? We are using (as many other ios application) it as the dependency manager for our app and would like to use FieryCrucible with our dependency manager. Currently we simply Copy-Paste the code, but it is hard to maintain.

Thank you!
Omer

**Comment by jkolb** [comment]
I wasn't planning on it, but am happy to add it since you requested it. I should be able to do it in the next few days.

**Comment by omerlh** [comment]
That's great to hear! thank you!

**Comment by jkolb** [comment]
OK I think it is ready to go, but would like to see if it works for you. So let me know when you get a chance to try it out. Thanks.

**Comment by omerlh** [comment]
Thank you for the quick response! I just updated our mobile app with the new pod...
