### ISSUE TITLE
Pass factory method parameters to contructor

### ISSUE THREAD

**Issue by jasperblues** [jkolb/FieryCrucible#18]
Given the following code: 

```swift
itemsDelegate.onSelect = { (item) in
            let controller = self.assembly.itemController()
            controller.stockItem = stockItem 
            self.navigationController!.pushViewController(controller, animated: true)
        }
```

And the DI factory

```
public class ApplicationAssembly: DependencyFactory {

    func itemController() -> CartController {
        return scoped(CartController(nibName: "ItemView", client: warehouseClient(), assembly: self)) {
            (controller) in
            controller.title = "Ascii Warehouse"
        }
    }
}

It would be nice if it was possible to write it as follows: 

```swift 
let controller = self.assembly.itemController(stockItem)
self.navigationController!.pushViewController(controller, animated: true)
```

Where the factory method passes the stockItem param into the init method. Is this possible?

**Comment by jasperblues** [comment]
Tested - it works fine. Don't know why I thought it wouldn't.

**Comment by jkolb** [comment]
While you technically can do this I have run into the case where another place needs access to the same object during the same request, but doesn't know which parameter to pass in. Since it will get a cached instance it doesn't really matter, but it is a bit awkward.

I don't really know how other DI systems handle this (I'm actually a DI newbie still). My gut feeling though is that DI factory methods must never take parameters as all places that call that method may not have access to the parameter.

**Comment by jasperblues** [comment]
It is a common case that you want to instantiate a class with some static dependencies wired up, along with something known only at runtime. Eg, in the example above we have a CartController with a client wired in, and then a StockItem instance known at runtime. 

We can easily create a factory class that emits the instance we want. 

```swift

class CartControllerFactory {

    private(set) var NetworkClient
    init (networkClient: NetworkClient) {
        self.networkClient = networkClient
    }

    func controllerWithStockItem(stockItem: StockItem) {
        return CartController(stockItem: stockItem, networkClient: networkClient)
    }
}
```

In Typhoon (heavier DI framework that uses the Objective-C runtime) we thought it would be nice to just use the DI assembly as such a factory, for top-level classes, to get the lower-level dependencies injected in. 

Its still possible to run into the problem you described with circular dependencies - such as a controller with a custom view, and the custom view's delegate is the controller. Typhoon, for better or worse, detects and handles this. 

https://github.com/appsquickly/Typhoon/wiki/Propagating-runtime-arguments#propagating-run-time-arguments-through-to-dependencies

**Comment by jasperblues** [comment]
Added a link to this lib from Typhon : https://github.com/appsquickly/Typhoon

**Comment by jkolb** [comment]
Thank you for the vote of confidence.

**Comment by jasperblues** [comment]
Thanks for the nice lib - had fun using it.
