### ISSUE TITLE
Difference between factory and configure

### ISSUE THREAD

**Issue by Atimca** [jkolb/FieryCrucible#20]
Hello! Very nice lib! However, I have a question. What's the difference between factory and configure? 

In your own example, you put some configure stuff into the factory closure.

`factory: {
				let instance = UIWindow(frame: UIScreen.mainScreen().bounds)
				instance.backgroundColor = UIColor.whiteColor()
				return instance
			},
			configure: { instance in
				instance.rootViewController = self.rootViewController()
			}`

In the code of the library, I understood, that you are using some delay stuff but I still not understand, why.

**Comment by jkolb** [comment]
Building up objects proceeds in two stages. First all the objects are created and initialized and then they are hooked together. For example an object and its delegate must both be created and initialized before they can reference each other. 

Factory creates the objects and optionally allows you to set properties on that object before that object is accessible to other objects. 

Configuration is mostly for hooking up two onjects together but can also be used to set additional properties that don’t have other objects relying on that state.

**Comment by Atimca** [comment]
@jkolb thx for the fast response. I got it.
