### ISSUE TITLE
Minimum deployment target

### ISSUE THREAD

**Issue by daneov** [jkolb/FieryCrucible#21]
Currently it's set at ios 11.2. 

Is there a specific reason for this?

**Comment by jkolb** [comment]
Neither the project file or the pod spec require 11.2 as far as I can tell. Are you using CocoaPods, Carthage, Swift Package Manager, or directly including the project into yours?

**Comment by daneov** [comment]
Carthage :)

**Comment by jkolb** [comment]
OK updated the project to have deployment targets for iOS 8.0
